### ISSUE TITLE
Can't use NuGet package on OSX arm64

### ISSUE THREAD

**Issue by endel** [StirlingLabs/MsQuic.Net#3]
Hi there, I'm trying to use the NuGet package but I'm getting this error:

```
System.TypeInitializationException: "The type initializer for 'StirlingLabs.MsQuic.QuicRegistration' threw an exception." --->
System.TypeInitializationException: "The type initializer for 'StirlingLabs.MsQuic.Bindings.MsQuic' threw an exception." --->
System.DllNotFoundException: "Missing MsQuic native library."
  at at StirlingLabs.MsQuic.Bindings.MsQuic..cctor()
  --- End of inner exception stack trace ---
  at at StirlingLabs.MsQuic.Bindings.MsQuic.Init()\n   at StirlingLabs.MsQuic.QuicRegistration..cctor()
  --- End of inner exception stack trace ---
  at StirlingLabs.MsQuic.QuicRegistration..ctor(String name)\n   at Program.<<Main>$>d__0.MoveNext() in
```

By looking at the `StirlingLabs.MsQuic.Bindings.osx/osx.csproj` file, it mentions [the bindings are specific to x86](https://github.com/StirlingLabs/MsQuic.Net/blob/bdbf9fc5dd85e798efe895c86d7600a6b25dcdfe/StirlingLabs.MsQuic.Bindings.osx/osx.csproj#L41)

If possible could you guide me on how I could build this project for arm64?
Thank you!

**Comment by Rjvs** [comment]
Hi @endel we're actively looking into this problem on a couple of fronts but don't have an immediate solution (progress is slower than I'd like because we don't have any M1 Macs).

**Comment by TYoungSL** [comment]
The description (the x86 bit) is just copy-pasta, we need to verify the dylib we picked up from the msquic repo is a fat binary with arm64 support and we're picking it.

**Comment by TYoungSL** [comment]
Closing for inactivity.

**Comment by Rjvs** [comment]
Just to comment that this is fixed in main, which uses universal binary versions of msquic that we build.
